### ISSUE TITLE
Tussenbeoordeling opdracht 2

### ISSUE THREAD

**Issue by pp-koch** [nlvo/browser-technologies-1920#2]
Je hebt nog het een en ander te doen, maar dat wist je zelf ook al. Tip: maak een To Do lijst en zet die in de Readme; dat is makkelijk voor mij, zodat ik je niet wijs op dingen die je al lang wist.

Je vragen:

    In hoeverre is mijn HTML semantisch, soms kan het namelijk zijn dat ik iets voor het gemak doe. En vergeet ik het semantische aspect.
    
Dit is prima. Niets aan veranderen.
    
    Tips voor goede resources over semantisch HTML. Vaak gaan meeste niet verder dan simpel section > article. Maar wat gebeurt er als ik een wat grotere website heb waar meer wordt genest.

Ik heb even gezocht, en je hebt gelijk: er zijn niet veel gevorderde resources over semantische HTML. Ik heb de vraag op Twitter uitgezet; als er een nuttig antwoord komt, laat ik het je weten.

**Comment by pp-koch** [comment]
Update: kijk eens naar deze twee sites. Ze zijn allebei verzamelingen van artikelen, en geen gestructureerde resource, maar best de moeite waard:

http://html5doctor.com/
https://adrianroselli.com/

**Comment by pp-koch** [comment]
Een hele gedegen documentatie van het BBC-systeem van semantic HTML:

https://bbc.github.io/gel/

**Comment by nlvo** [comment]
Oh dankjewel! Hier kan ik zeker mee verder. Ik zal zeker een [todo](https://github.com/nlvo/browser-technologies-1920/projects/1) lijst maken!
